# Generated by Django 3.2.3 on 2021-06-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('entete_service', models.TextField()),
                ('image_newsletter', models.FileField(upload_to='images')),
                ('entete_newsletter', models.TextField()),
                ('entete_contact', models.TextField()),
                ('instruction_contact', models.TextField()),
                ('copyright', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Sociaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
                ('lien', models.URLField()),
            ],
            options={
                'verbose_name': 'social',
                'verbose_name_plural': 'Sociaux',
            },
        ),
        migrations.CreateModel(
            name='Temoingnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('nom', models.CharField(max_length=250)),
                ('profession', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Temoingnage',
                'verbose_name_plural': 'Temoingnages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='images')),
                ('profession', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=250)),
                ('nom_site', models.CharField(max_length=250)),
                ('logo_site', models.CharField(max_length=250)),
                ('adresse', models.CharField(max_length=250)),
                ('mapp', models.TextField()),
                ('email', models.CharField(max_length=250)),
                ('slogan', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'wensite',
                'verbose_name_plural': 'wensites',
            },
        ),
    ]
