# Generated by Django 3.2.2 on 2021-06-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_blog_user'),
        ('website', '0002_configuration_sociaux_temoingnage_user_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
