# Generated by Django 3.2.2 on 2021-06-01 14:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profils'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'website', 'verbose_name_plural': 'websites'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='sociaux',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='sociaux',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='temoingnage',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='temoingnage',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='entete_contact',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='entete_newsletter',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='entete_service',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='instruction_contact',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='website',
            name='slogan',
            field=tinymce.models.HTMLField(),
        ),
    ]
