# Generated by Django 3.2.2 on 2021-06-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='updated_at',
            new_name='date_update',
        ),
    ]
