# Generated by Django 3.2.3 on 2021-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoingnage',
            name='nom',
            field=models.CharField(default='Zoe Maye', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temoingnage',
            name='profession',
            field=models.CharField(default='Digital Marketing', max_length=250),
            preserve_default=False,
        ),
    ]
