# Generated by Django 3.2.3 on 2021-06-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210601_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optionservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Optionservice',
                'verbose_name_plural': 'Optionservices',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='description_video',
            field=models.TextField(default='https://www.youtube.com/embed/myVN26Vx4MU?controls=0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.URLField(default='Curabitur egestas mollis tellus sit amet porttitor. Sed leo nisl, posuere at molestie ac, suscipit auctor mauris. Etiam quis metus elementum, tempor risus vel', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Proposservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='images')),
                ('optionservice', models.ManyToManyField(null=True, related_name='optionservice', to='service.Optionservice')),
            ],
            options={
                'verbose_name': 'Proposservice',
                'verbose_name_plural': 'Proposservices',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='proposservice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposservice', to='service.proposservice'),
        ),
    ]
