# Generated by Django 3.2.3 on 2021-06-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_configuration_sociaux_temoingnage_user_website'),
        ('service', '0003_auto_20210601_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='images')),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorieblog', to='service.categorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user', verbose_name='auteur')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Categorieblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'categorieblog',
                'verbose_name_plural': 'categorieblogs',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
            },
        ),
        migrations.RemoveField(
            model_name='proposservice',
            name='optionservice',
        ),
        migrations.DeleteModel(
            name='Temoingnage',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description_video',
            new_name='conclusion',
        ),
        migrations.RemoveField(
            model_name='service',
            name='proposservice',
        ),
        migrations.AddField(
            model_name='service',
            name='image_pricipal',
            field=models.FileField(default='1', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='introduction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='nom',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='nom_compagny',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_soustitre',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Optionservice',
        ),
        migrations.DeleteModel(
            name='Proposservice',
        ),
    ]
