# Generated by Django 3.2.2 on 2021-06-01 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0005_remove_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auteur_blog', to='auth.user'),
            preserve_default=False,
        ),
    ]
