# Generated by Django 3.2.2 on 2021-06-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_blog_auteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='categorieblog',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='categorieblog',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='commentaire',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='created_at',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='updated_at',
            new_name='date_update',
        ),
        migrations.AlterField(
            model_name='blog',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorieblog', to='service.categorieblog'),
        ),
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.FileField(upload_to='images'),
        ),
    ]
